config/routes.rb
Rails.application.routes.draw do
  resources :equipos
  resources :fabricantes
  resources :tipo_equipos
  # get '/home', to: 'home#index'
  get '/', to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/equipo.rb
class Equipo < ApplicationRecord
    self.primary_key = "id"
    belongs_to :fabricante
    belongs_to :tipo_equipo
    validates :descripcion, presence: true
    validates :fabricante_id, presence: true
    validates :consultorio_id, presence: true
    validates :fecha_adquisicion, presence: true
    validates :tipo_equipo_id, presence: true
end

app/models/fabricante.rb
class Fabricante < ApplicationRecord
    self.primary_key = "id"
    validates :descripcion, presence: true
end

app/models/tipo_equipo.rb
class TipoEquipo < ApplicationRecord
    self.primary_key = "id"
    validates :descripcion, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

app/controllers/equipos_controller.rb
class EquiposController < ApplicationController
  before_action :set_equipo, only: [:show, :edit, :update, :destroy]

  # GET /equipos
  # GET /equipos.json
  def index
    # @equipos = Equipo.all
    @equipos = Equipo.paginate(:page => params[:page], :per_page => 9)
    render 'equipos/list'
  end

  # GET /equipos/1
  # GET /equipos/1.json
  def show
  end

  # GET /equipos/new
  def new
    @equipo = Equipo.new
    @fabricantes = Fabricante.new
    # @fabricantes = @fabricantes->
    render 'equipos/new'
  end

  # GET /equipos/1/edit
  def edit
  end

  # POST /equipos
  # POST /equipos.json
  def create
    @equipo = Equipo.new(equipo_params)

    respond_to do |format|
      if @equipo.save
        format.html { redirect_to @equipo, notice: 'Equipo ah sido creado.' }
        format.json { render :show, status: :created, location: @equipo }
      else
        format.html { render :new }
        format.json { render json: @equipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipos/1
  # PATCH/PUT /equipos/1.json
  def update
    respond_to do |format|
      if @equipo.update(equipo_params)
        format.html { redirect_to @equipo, notice: 'Equipo ah sido actualizado.' }
        format.json { render :show, status: :ok, location: @equipo }
      else
        format.html { render :edit }
        format.json { render json: @equipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipos/1
  # DELETE /equipos/1.json
  def destroy
    @equipo.destroy
    respond_to do |format|
      format.html { redirect_to equipos_url, notice: 'Equipo ah sido eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipo
      @equipo = Equipo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipo_params
      params.require(:equipo).permit(:descripcion, :tipo_equipo_id, :fabricante_id, :consultorio_id, :fecha_adquisicion)
    end
end

app/controllers/fabricantes_controller.rb
class FabricantesController < ApplicationController
  before_action :set_fabricante, only: [:show, :edit, :update, :destroy]

  # GET /fabricantes
  # GET /fabricantes.json
  def index
    @fabricantes = Fabricante.all
    @fabricantes  = Fabricante.paginate(:page => params[:page], :per_page => 10)
    render 'fabricantes/list'
  end

  # GET /fabricantes/1
  # GET /fabricantes/1.json
  def show
  end

  # GET /fabricantes/new
  def new
    @fabricante = Fabricante.new
    render 'fabricantes/new'
  end

  # GET /fabricantes/1/edit
  def edit
    @fabricante = Fabricante.find(params[:id])
    render 'fabricantes/edit'
  end

  # POST /fabricantes
  # POST /fabricantes.json
  def create
    @fabricante = Fabricante.new(fabricante_params)

    respond_to do |format|
      if @fabricante.save
        format.html { redirect_to @fabricante, notice: 'Fabricante was successfully created.' }
        format.json { render :show, status: :created, location: @fabricante }
      else
        format.html { render :new }
        format.json { render json: @fabricante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fabricantes/1
  # PATCH/PUT /fabricantes/1.json
  def update
    respond_to do |format|
      if @fabricante.update(fabricante_params)
        format.html { redirect_to @fabricante, notice: 'Fabricante was successfully updated.' }
        format.json { render :show, status: :ok, location: @fabricante }
      else
        format.html { render :edit }
        format.json { render json: @fabricante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fabricantes/1
  # DELETE /fabricantes/1.json
  def destroy
    @fabricante.destroy
    respond_to do |format|
      format.html { redirect_to fabricantes_url, notice: 'Fabricante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fabricante
      @fabricante = Fabricante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fabricante_params
      params.require(:fabricante).permit(:descripcion)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	render 'layouts/appb'
	end
	
	def new 

	end 
end

app/controllers/tipo_equipos_controller.rb
class TipoEquiposController < ApplicationController
  before_action :set_tipo_equipo, only: [:show, :edit, :update, :destroy]

  # GET /tipo_equipos
  # GET /tipo_equipos.json
  def index
    # @tipo_equipos = TipoEquipo.all
    @tipo_equipos = TipoEquipo.paginate(:page => params[:page], :per_page => 9)
    render 'tipo_equipos/list'
  end

  # GET /tipo_equipos/1
  # GET /tipo_equipos/1.json
  def show
  end

  # GET /tipo_equipos/new
  def new
    @tipo_equipo = TipoEquipo.new
    render 'tipo_equipos/new'
  end

  # GET /tipo_equipos/1/edit
  def edit
  end

  # POST /tipo_equipos
  # POST /tipo_equipos.json
  def create
    @tipo_equipo = TipoEquipo.new(tipo_equipo_params)

    respond_to do |format|
      if @tipo_equipo.save
        format.html { redirect_to @tipo_equipo, notice: 'Tipo equipo was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_equipo }
      else
        format.html { render :new }
        format.json { render json: @tipo_equipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_equipos/1
  # PATCH/PUT /tipo_equipos/1.json
  def update
    respond_to do |format|
      if @tipo_equipo.update(tipo_equipo_params)
        format.html { redirect_to @tipo_equipo, notice: 'Tipo equipo was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_equipo }
      else
        format.html { render :edit }
        format.json { render json: @tipo_equipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_equipos/1
  # DELETE /tipo_equipos/1.json
  def destroy
    @tipo_equipo.destroy
    respond_to do |format|
      format.html { redirect_to tipo_equipos_url, notice: 'Tipo equipo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_equipo
      @tipo_equipo = TipoEquipo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_equipo_params
      params.require(:tipo_equipo).permit(:descripcion)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/equipo_controller_helper.rb
module EquipoControllerHelper
end

app/helpers/equipos_helper.rb
module EquiposHelper
end

app/helpers/fabricante_controller_helper.rb
module FabricanteControllerHelper
end

app/helpers/fabricante_helper.rb
module FabricanteHelper
end

app/helpers/fabricantes_helper.rb
module FabricantesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tipo_equipo_controller_helper.rb
module TipoEquipoControllerHelper
end

app/helpers/tipo_equipo_helper.rb
module TipoEquipoHelper
end

app/helpers/tipo_equipos_helper.rb
module TipoEquiposHelper
end

app/views/equipo_controller/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>UMM - Universidad Metropolitana de Monterrey</title>

    <!-- Bootstrap Core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="vendor/morrisjs/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesnt work if you view the page via file: -->
    <!-- [if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif] -->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">UMM</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="home"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                            <a href="/equipos"><i class="fa fa-dashboard fa-fw"></i> Equipos</a>
                            <a href="/fabricantes"><i class="fa fa-dashboard fa-fw"></i> Fabricantes</a>
                            <a href="/tipo-de-equipos"><i class="fa fa-dashboard fa-fw"></i> Tipo de Equipos</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-wrench fa-fw"></i> UI Elements<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="panels-wells.html">Panels and Wells</a>
                                </li>
                                <li>
                                    <a href="buttons.html">Buttons</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h3 class="page-header">Dashboard</h3>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            
            <div class="row">

            
                <div class="col-lg-12">
                    
                </div>
                <!-- /.col-lg-12 -->
            </div>

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="vendor/metisMenu/metisMenu.min.js"></script>

    <!-- Morris Charts JavaScript -->
    <script src="vendor/raphael/raphael.min.js"></script>
    <script src="vendor/morrisjs/morris.min.js"></script>
    <script src="data/morris-data.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="dist/js/sb-admin-2.js"></script>

</body>

</html>

app/views/equipos/_form.html.erb
<%= form_with(model: equipo, local: true) do |form| %>
  <% if equipo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(equipo.errors.count, "error") %> prohibited this equipo from being saved:</h2>

      <ul>
      <% equipo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion, { :class => "form-control", placeholder: "Descripción" } %>
  </div>

  <div class="form-group">
    <%= form.label :tipo_equipo_id %>
    <%= form.number_field :tipo_equipo_id, { :class => "form-control", placeholder: "Tipo de equipo" } %>
  </div>

  <div class="form-group">
    <%= form.label :fabricante_id %>
    <%= form.number_field :fabricante_id, { :class => "form-control", placeholder: "Fabricante" } %>
  </div>

  <div class="form-group">
    <%= form.label :consultorio_id %>
    <%= form.number_field :consultorio_id, { :class => "form-control", placeholder: "Consultorio" } %>
  </div>

  <div class="form-group">
    <%= form.label :fecha_adquisicion %>
    <%= form.text_field :fecha_adquisicion, { :class => "form-control", placeholder: "Fecha Adquisicion" } %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/equipos/edit.html.erb
<% content_for :content do %>
    <%= render 'form', equipo: @equipo %>
    
    <%= link_to 'Show', @equipo, {:class=>"btn btn-success btn-sm"}  %>
    <%= link_to 'Back', equipos_path, {:class=>"btn btn-warning btn-sm"} %>
<% end %>

<% content_for :title do %> 
    Editing Equipo 
<% end %>

<%= render template: 'layouts/appb' %>

app/views/equipos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Equipos</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Tipo equipo</th>
      <th>Fabricante</th>
      <th>Consultorio</th>
      <th>Fecha adquisicion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @equipos.each do |equipo| %>
      <tr>
        <td><%= equipo.descripcion %></td>
        <td><%= equipo.tipo_equipo_id %></td>
        <td><%= equipo.fabricante_id %></td>
        <td><%= equipo.consultorio_id %></td>
        <td><%= equipo.fecha_adquisicion %></td>
        <td><%= link_to 'Show', equipo %></td>
        <td><%= link_to 'Edit', edit_equipo_path(equipo) %></td>
        <td><%= link_to 'Destroy', equipo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Equipo', new_equipo_path %>

app/views/equipos/list.html.erb
<% content_for :content do %>
    <div class="panel panel-default">
        <div class="panel-body" style="padding-right:0;padding-left:0;">
            <table class="table table-striped">
                <thead>
                    <tr>
                    <th>Descripcion</th>
                    <th colspan="3"></th>
                    </tr>
                </thead>

                <tbody>
                    <% @equipos.each do |equipo| %>
                    <tr>
                        <td><%= equipo.descripcion %></td>
                        <td><%= link_to 'Show', equipo, {:class=>"btn btn-primary btn-sm"} %></td>
                        <td><%= link_to 'Edit', edit_equipo_path(equipo), {:class=>"btn btn-success btn-sm"} %></td>
                        <td><%= link_to 'Destroy', equipo, method: :delete, data: { confirm: 'Are you sure?'}, :class=>'btn btn-warning btn-sm' %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>

        <div class="panel-footer">
            <div class="digg_pagination">
                <div class="page_info">
                    <%= page_entries_info @equipos %>
                </div>
                <%= will_paginate @equipos, :container => false %>
            </div>
        </div>

    </div>

<% end %>

<% content_for :title do %> 
    Listado <%= link_to 'New','equipos/new', {:class=>"btn btn-info btn-sm",:style=>"float:right;margin-top:-10;"} %> 
<% end %>

<%= render template: 'layouts/appb' %>

app/views/equipos/new.html.erb
<% content_for :content do %>

    <%= render 'form', equipo: @equipo %>
    
    <%= link_to 'Show', @equipo, { :class => "btn btn-success btn-sm" } %>
    
    <%= link_to 'Back', equipos_path, { :class => "btn btn-warning btn-sm" } %>

<% end %>

<% content_for :title do %> 
    New Equipo
<% end %>

<%= render template: 'layouts/appb' %>

app/views/equipos/show.html.erb
<% content_for :content do %>
  
  
  <p>
    <strong>Descripcion:</strong>
    <%= @equipo.descripcion %>
  </p>

  <p>
    <strong>Tipo equipo:</strong>
    <%= @equipo.tipo_equipo_id %>
  </p>

  <p>
    <strong>Fabricante:</strong>
    <%= @equipo.fabricante_id %>
  </p>

  <p>
    <strong>Consultorio:</strong>
    <%= @equipo.consultorio_id %>
  </p>

  <p>
    <strong>Fecha adquisicion:</strong>
    <%= @equipo.fecha_adquisicion %>
  </p>


  <%= link_to 'Edit', edit_equipo_path(@equipo), {:class=>"btn btn-primary btn-sm"}  %> |
  <%= link_to 'Back', equipos_path, {:class=>"btn btn-warning btn-sm"} %>
<% end %>

<% content_for :title do %> 
  Show Equipo 
<% end %>

<%= render template: 'layouts/appb' %>

app/views/fabricantes/_form.html.erb
<div>
  <%= form_with model: fabricante do |form| %>
    <% if fabricante.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(fabricante.errors.count, "error") %> prohibited this equipo from being saved:</h2>

        <ul>
        <% fabricante.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :descripcion %>
      <%= form.text_field :descripcion, { :class => "form-control", placeholder: "Descripción" }  %>
    </div>

    <div class="actions">
      <%= form.submit :class => "btn btn-primary btn-sm" %>
    </div>
  <% end %>
</div>

app/views/fabricantes/edit.html.erb
<% content_for :content do %>
    <%= render 'form', fabricante: @fabricante %>
    
    <%= link_to 'Show', @fabricante, {:class=>"btn btn-success btn-sm"}  %>
    <%= link_to 'Back', fabricantes_path, {:class=>"btn btn-warning btn-sm"} %>
<% end %>

<% content_for :title do %> 
    Editing Fabricante 
<% end %>

<%= render template: 'layouts/appb' %>

app/views/fabricantes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fabricantes</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fabricantes.each do |fabricante| %>
      <tr>
        <td><%= fabricante.descripcion %></td>
        <td><%= link_to 'Show', fabricante %></td>
        <td><%= link_to 'Edit', edit_fabricante_path(fabricante) %></td>
        <td><%= link_to 'Destroy', fabricante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fabricante', new_fabricante_path %>

app/views/fabricantes/list.html.erb
<% content_for :content do %>

    <div class="panel panel-default">
        <div class="panel-body" style="padding-right:0;padding-left:0;">
            <table class="table table-striped">
                <thead>
                    <tr>
                    <th>Descripcion</th>
                    <th colspan="3"></th>
                    </tr>
                </thead>

                <tbody>
                    <% @fabricantes.each do |fabricante| %>
                    <tr>
                        <td><%= fabricante.descripcion %></td>
                        <td><%= link_to 'Show', fabricante, {:class=>"btn btn-primary btn-sm"} %></td>
                        <td><%= link_to 'Edit', edit_fabricante_path(fabricante), {:class=>"btn btn-success btn-sm"} %></td>
                        <td><%= link_to 'Destroy', fabricante, method: :delete, data: { confirm: 'Are you sure?'}, :class=>'btn btn-warning btn-sm' %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>

        <div class="panel-footer">
            <div class="digg_pagination">
                <div class="page_info">
                    <%= page_entries_info @fabricantes %>
                </div>
                <%= will_paginate @fabricantes, :container => false %>
            </div>
        </div>
            
    </div>

<% end %>

<% content_for :title do %> 
    Listado <%= link_to 'New','fabricantes/new', {:class=>"btn btn-info btn-sm",:style=>"float:right;margin-top:-10;"} %> 
<% end %>

<%= render template: 'layouts/appb' %>

app/views/fabricantes/new.html.erb
<% content_for :content do %>
    <%= render 'form', fabricante: @fabricante %>
    
    <%= link_to 'Show', @fabricante, {:class=>"btn btn-success btn-sm"}  %>
    <%= link_to 'Back', fabricantes_path, {:class=>"btn btn-warning btn-sm"} %>
<% end %>

<% content_for :title do %> 
    New Fabricante
<% end %>

<%= render template: 'layouts/appb' %>

app/views/fabricantes/show.html.erb
<% content_for :content do %>
  
  <form>
    <div class="form-group">
      <label><strong>Descripcion:</strong></label>
      <%= @fabricante.descripcion %>
    </div>
  </form>

  <%= link_to 'Edit', edit_fabricante_path(@fabricante), {:class=>"btn btn-primary btn-sm"}  %> |
  <%= link_to 'Back', fabricantes_path, {:class=>"btn btn-warning btn-sm"} %>
<% end %>

<% content_for :title do %> 
  Show Fabricante 
<% end %>

<%= render template: 'layouts/appb' %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_test.html.erb
<h1>Hola mundo</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UMM - Universidad Metropolitana de Monterrey</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tipo_equipos/edit.html.erb
<% content_for :content do %>
    <%= render 'form', tipo_equipo: @tipo_equipo %>
    
    <%= link_to 'Show', @tipo_equipo, {:class=>"btn btn-success btn-sm"}  %> | 
    <%= link_to 'Back', tipo_equipos_path, {:class=>"btn btn-warning btn-sm"} %>
<% end %>

<% content_for :title do %> 
    Editing Tipo de Equipo 
<% end %>

<%= render template: 'layouts/appb' %>

app/views/tipo_equipos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipo Equipos</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_equipos.each do |tipo_equipo| %>
      <tr>
        <td><%= tipo_equipo.descripcion %></td>
        <td><%= link_to 'Show', tipo_equipo %></td>
        <td><%= link_to 'Edit', edit_tipo_equipo_path(tipo_equipo) %></td>
        <td><%= link_to 'Destroy', tipo_equipo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipo Equipo', new_tipo_equipo_path %>

app/views/tipo_equipos/list.html.erb
<% content_for :content do %>
    <div class="panel panel-default">
        <div class="panel-body" style="padding-right:0;padding-left:0;">
            <table class="table table-striped">
                <thead>
                    <tr>
                    <th>Descripcion</th>
                    <th colspan="3"></th>
                    </tr>
                </thead>

                <tbody>
                    <% @tipo_equipos.each do |tipo| %>
                    <tr>
                        <td><%= tipo.descripcion %></td>
                        <td><%= link_to 'Show', tipo, {:class=>"btn btn-primary btn-sm"} %></td>
                        <td><%= link_to 'Edit', edit_tipo_equipo_path(tipo), {:class=>"btn btn-success btn-sm"} %></td>
                        <td><%= link_to 'Destroy', tipo, method: :delete, data: { confirm: 'Are you sure?'}, :class=>'btn btn-warning btn-sm' %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>

        <div class="panel-footer">
            <div class="digg_pagination">
                <div class="page_info">
                <%= page_entries_info @tipo_equipos %>
                </div>
                <%= will_paginate @tipo_equipos, :container => false %>
            </div>
        </div>

    </div>

<% end %>

<% content_for :title do %> 
    Listado <%= link_to 'New','tipo_equipos/new', {:class=>"btn btn-info btn-sm",:style=>"float:right;margin-top:-10;"} %> 
<% end %>

<%= render template: 'layouts/appb' %>

app/views/tipo_equipos/new.html.erb
<% content_for :content do %>
    <%= render 'form', tipo_equipo: @tipo_equipo %>
    
    <%= link_to 'Show', @tipo_equipo, {:class=>"btn btn-success btn-sm"}  %>
    <%= link_to 'Back', tipo_equipos_path, {:class=>"btn btn-warning btn-sm"} %>
<% end %>

<% content_for :title do %> 
    New Tipo de Equipo
<% end %>

<%= render template: 'layouts/appb' %>

app/views/tipo_equipos/show.html.erb
<% content_for :content do %>
  
  <form>
    <div class="form-group">
      <label><strong>Descripcion:</strong></label>
      <%= @tipo_equipo.descripcion %>
    </div>
  </form>

  <%= link_to 'Edit', edit_tipo_equipo_path(@tipo_equipo), {:class=>"btn btn-primary btn-sm"}  %> |
  <%= link_to 'Back', tipo_equipos_path, {:class=>"btn btn-warning btn-sm"} %>
<% end %>

<% content_for :title do %> 
  Show Tipo de Equipo 
<% end %>

<%= render template: 'layouts/appb' %>